name: DeployCheck
on: pull_request

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: starter
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - name: Build
        run: |    
          sudo apt update
          sudo apt-get -y install cargo libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
          cargo install tauri-cli
          sudo yarn global add react-scripts
          rm -f package-lock.json
          yarn install
          yarn tauri build
