name: DeployCheck
on: pull_request

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: starter
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev libayatana-appindicator3-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'      

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install app dependencies and build web
        run: yarn

      - name: Build the app
        uses: tauri-apps/tauri-action@v0

