on:
  workflow_dispatch:

jobs:
  build-starter:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
      - run: |
          ls
          yarn tauri build
