name: Publish
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: paulhatch/semantic-version@v4.0.2
        id: versioning
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}"
          # Optional path to check for changes. If any changes are detected in the path the
          # 'changed' output will true. Enter multiple paths separated by spaces.
          change_path: "."
          # Named version, will be used as suffix for name version tag
          namespace: ""
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: false
            - name: Update version of Package.json
        run: |     
          NEW_VERSION=${{ steps.versioning.outputs.version }}
          CURRENT_VERSION=$(node -p "require('./package.json').version") 
          sed -i '' "s/${CURRENT_VERSION}/${NEW_VERSION}/" package.json
          git add package.json
          git commit -m "bump version"
          cat package.json
          git push
      - name: Build
        run: |
          sudo apt update
          sudo apt-get -y install cargo
          sudo apt install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
          cargo install tauri-cli
          sudo yarn global add react-scripts
          rm -f package-lock.json
          yarn install
          yarn build
          cargo-tauri build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ steps.versioning.outputs.version }}
          title: ${{ steps.versioning.outputs.version }}
          files: |
            LICENSE.md
            ./src-tauri/target/release/bundle/deb/*.deb
            ./src-tauri/target/release/bundle/appimage/*.AppImage
            ./src-tauri/target/release/manjaro-starter