name: Publish
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v1
      - name: Update version of Package.json
        run: |    
          NEW_VERSION=${{ steps.versioning.outputs.version }}
          CURRENT_VERSION=$(node -p "require('./package.json').version") 
          sed -i "s/${CURRENT_VERSION}/${NEW_VERSION}/" package.json
          git add package.json
          git commit -m "bump version"
          git push
          git pull
          sudo apt update
          sudo apt-get -y install cargo
          sudo apt install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
          cargo install tauri-cli
          sudo yarn global add react-scripts
          rm -f package-lock.json
          yarn install
          yarn build
          cargo-tauri build
          
      - name: Conventional Changelog Action
        id: changelog 
        uses: TriPSs/conventional-changelog-action@v3 
        with: 
            github-token: ${{ secrets.GITHUB_TOKEN }}
            output-file: "false" 
      - uses: "softprops/action-gh-release@v1"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: false
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          automatic_release_tag: ${{ steps.versioning.outputs.version }}
          files: |
            LICENSE.md
            ./src-tauri/target/release/bundle/deb/*.deb
            ./src-tauri/target/release/bundle/appimage/*.AppImage