name: Publish
on:
  workflow_dispatch:

jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt update
        sudo apt-get -y install cargo
        cargo install tauri-cli
        sudo yarn global add react-scripts
        yarn build
        cargo-tauri build
